<a href="https://colab.research.google.com/github/myrayunus/WIA1007-data-science/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Tutorial 3
import numpy as np

#1. Create a numpy array of size 2x2
array1 = np.array([[1,2],[3,4]])
print(array1)

[[1 2]
 [3 4]]


In [8]:
#2. Create a random numpy array of size 3 x 4
import numpy as np

array2 = np.random.random((3,4))
print(array2)

[[0.36930059 0.12726872 0.58053783 0.76600691]
 [0.40746722 0.82053412 0.42627169 0.4903055 ]
 [0.89952761 0.19668011 0.35364284 0.76837678]]


In [12]:
#3. Create a numpy array of ones and a numpy array of zeroes
import numpy as np

array_ones = np.ones((2, 3))
print("Ones:")
print(array_ones)

array_zeros = np.zeros((3, 2))
print("\nZeros:")
print(array_zeros)
print("")

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Zeros:
[[0. 0.]
 [0. 0.]
 [0. 0.]]



In [10]:
#4. Create a random numpy array of size 6x3 and transpose it
import numpy as np

def transpose_array():
  original_array = np.random.rand(6,3)
  transposed_array = original_array.T
  print("Original array: ")
  print(original_array)
  print(" Transposed array:  ")
  print(transposed_array)

transpose_array()

Original array: 
[[0.36471588 0.41594916 0.5376221 ]
 [0.97955465 0.06464317 0.65246501]
 [0.32140988 0.62618821 0.40121536]
 [0.80729023 0.36413453 0.39282948]
 [0.78259082 0.35715226 0.85360302]
 [0.91740386 0.34303495 0.65807331]]
 Transposed array:  
[[0.36471588 0.97955465 0.32140988 0.80729023 0.78259082 0.91740386]
 [0.41594916 0.06464317 0.62618821 0.36413453 0.35715226 0.34303495]
 [0.5376221  0.65246501 0.40121536 0.39282948 0.85360302 0.65807331]]


In [11]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
import numpy as np
n=int(input("Enter n:"))
p=int(input("Enter p:"))
m=int(input("Enter m:"))

def dot_product(n,p,m):
  array_A = np.random.rand(n,p)
  array_B = np.random.rand(p,m)
  dot_product = array_A @ array_B
  return dot_product

dot_product = dot_product(n,p,m)
print(dot_product)

Enter n:2
Enter p:2
Enter m:1
[[0.60166589]
 [0.86525257]]
